spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Datasource configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/blueprints_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
